### ISSUE TITLE
Licensing issue

### ISSUE THREAD

**Issue by ghost** [PureAsbestos/grafx2-aseprite-shim#1]
As *GrafX2* source licensed under **GPLv2-only**, seems like you can't reuse *GrafX2 API* under **MIT**.

Maybe @pulkomandy could correct me or clarify this state.

**Comment by pulkomandy** [comment]
I think it is fine. The scripts (and in particular Dawnbringer's excellent toolbox) are not part of grafx2, and even if they were, since they are scripts, distributing them automatically complies with the gpl.

Moreover, the gpl applies only when you distribute software. If you are not distributing any part of grafx2, you are safe.

I am very happy to see the code under MIT, the use of GPL for GrafX2 is a decision of the original authors, and, if that's needed, I'll relicence any part of it that I wrote under MIT without any problem.

Just have fun and docool things!
